/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 存活探针
         * @description 只证明进程活着，不碰数据库。
         */
        get: operations["liveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 就绪探针
         * @description 确认依赖可用。数据库连不上时返回 503，让编排系统把流量摘掉。
         */
        get: operations["readiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 任务进度流（SSE）
         * @description 服务端推送任务状态、进度与模型的流式输出。
         *
         *     **全局单流**：不传参数时跟踪所有进行中的任务，事件里带 `task_id` 由前端分发。
         *     传 `batch_id` 只看某一批；传 `task_ids` 只看指定任务，且全部结束后连接会自动关闭。
         *
         *     事件类型：`snapshot`（连接时的全量快照）/ `progress` / `chunk`（模型输出分片）/ `done`（进入终态）。以 `:` 开头的行是心跳注释。
         */
        get: operations["streamTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务列表 */
        get: operations["listTasks"];
        put?: never;
        /**
         * 创建抽取任务
         * @description 为一批文档创建抽取任务并立即交给后台执行，**接口立刻返回不等待结果**。
         *
         *     进度通过 `GET /tasks/stream`（SSE）推送，或轮询 `GET /tasks/{id}`。
         *
         *     同一份文档可以用不同模板反复抽取，不需要重新上传文件。
         */
        post: operations["createTasks"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 任务详情 */
        get: operations["getTask"];
        put?: never;
        post?: never;
        /** 删除任务 */
        delete: operations["deleteTask"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 重新抽取
         * @description 把失败或已完成的任务重置为待执行并重新排队。
         *
         *     **会删除上一次的抽取结果**——不删的话，重跑失败时界面上会出现「任务失败但结果还在」的矛盾状态。
         */
        post: operations["retryTask"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks/{task_id}/result": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 获取抽取结果
         * @description 返回校验并规范化后的结构化数据，以及模型原始输出。
         *
         *     `warnings` 是非致命问题清单（字段缺失、类型被矫正、文档被截断等），用户可据此判断结果是否需要人工复核。
         */
        get: operations["getResult"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文档列表 */
        get: operations["listDocuments"];
        put?: never;
        /**
         * 上传文档（1 份或多份）
         * @description 接收 1~N 个文件，逐个校验、解析并入库。
         *
         *     **部分成功语义**：单个文件失败不会让整批回滚，失败项会出现在 `rejected` 中。
         *     内容完全相同的文件不会重复存储，会出现在 `duplicate` 中并复用已有记录。
         *
         *     状态码固定为 200：请求本身处理成功了，每个文件的结果在响应体里分别给出。用单一状态码表达「3 个成功 1 个失败」既做不到也不直观。
         */
        post: operations["uploadDocuments"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/documents/{document_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 文档详情 */
        get: operations["getDocument"];
        put?: never;
        post?: never;
        /**
         * 删除文档
         * @description **不可恢复的硬删除**。外键上是 ON DELETE CASCADE，该文档下的所有抽取任务与结果会一并被数据库删除。
         */
        delete: operations["deleteDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 模板列表
         * @description 返回全部可用模板：3 套内置模板（合同 / 简历 / 发票）在前，用户自定义模板在后。
         *
         *     每个字段都带中文 `label`，前端据此渲染结果卡片——用户看到的是「甲方」而不是 `party_a`。
         */
        get: operations["listTemplates"];
        put?: never;
        /**
         * 新建自定义模板
         * @description 传入标准 JSON Schema（Draft 2020-12），根节点必须是 object。
         *
         *     Schema 在入库前就会做完整性与合法性校验——**不能让一个语法错误的 schema 存进数据库**，否则用户要到建任务时才发现，而且报错点离问题源头很远。
         */
        post: operations["createCustomTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除自定义模板
         * @description 内置模板不可删除。
         *
         *     历史任务存的是模板快照（名称 + schema），因此删除模板**不影响**历史任务的展示与重跑。但有任务正在使用该模板时会拒绝删除。
         */
        delete: operations["deleteCustomTemplate"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 用量与成本统计
         * @description 累计的 token 用量、实际花费与成功率。
         *
         *     这组数字用来回答「这个功能一个月要花多少钱」「调大 max_tokens 值不值」，而不是把成本藏起来等月底看账单。
         */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * BatchUploadResponse
         * @description 批量上传结果。
         *
         *     采用「部分成功」语义：一个坏文件不会让整批回滚。
         *     用户拖 20 个文件进来时，因为其中一个格式不对就全军覆没是最反直觉的行为。
         */
        BatchUploadResponse: {
            /**
             * Accepted
             * @description 新入库的文档
             */
            accepted?: components["schemas"]["DocumentOut"][];
            /**
             * Duplicate
             * @description 内容已存在，直接复用已有记录
             */
            duplicate?: components["schemas"]["DocumentOut"][];
            /**
             * Rejected
             * @description 校验未通过的文件
             */
            rejected?: components["schemas"]["RejectedUpload"][];
        };
        /** Body_uploadDocuments */
        Body_uploadDocuments: {
            /**
             * Files
             * @description 待上传的文件，支持 .pdf / .docx / .txt / .md
             */
            files: string[];
        };
        /**
         * CustomTemplateCreate
         * @description 新建自定义模板。
         *
         *     字段名用 ``json_schema`` + 别名 ``schema``：``schema`` 是 Pydantic
         *     BaseModel 的保留名字，直接用作字段名会冲突，但对外的 JSON 又希望是
         *     ``schema`` 这个自然的名字，所以用别名并开启按名解析。
         */
        CustomTemplateCreate: {
            /**
             * Name
             * @description 模板名称，需唯一
             */
            name: string;
            /**
             * Schema
             * @description 标准 JSON Schema（Draft 2020-12），根节点必须是 object
             */
            schema: {
                [key: string]: unknown;
            };
            /** Description */
            description?: string | null;
            /**
             * Prompt Hint
             * @description 附加的业务规则，例如金额单位要求
             */
            prompt_hint?: string | null;
        };
        /** CustomTemplateOut */
        CustomTemplateOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Prompt Hint */
            prompt_hint: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** DocumentDeleteResponse */
        DocumentDeleteResponse: {
            /** Deleted */
            deleted: boolean;
            /**
             * Cascaded Tasks
             * @description 被连带删除的抽取任务数
             */
            cascaded_tasks: number;
        };
        /**
         * DocumentDetailOut
         * @description 文档详情。额外带上提取出的正文，便于排查抽取质量问题。
         *
         *     复用父类的 ``from_row``：``cls`` 在这里是 ``DocumentDetailOut``，
         *     因此会连同 ``text_content`` 一起映射出来。
         */
        DocumentDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Filename
             * @description 用户上传时的原始文件名，仅用于展示
             */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Sha256
             * @description 内容指纹，可用于判断是否为同一份文件
             */
            sha256: string;
            /** Page Count */
            page_count: number | null;
            /**
             * Char Count
             * @description 提取到的文本字符数
             */
            char_count: number;
            /**
             * Text Preview
             * @description 正文前 500 字，供列表预览
             */
            text_preview: string | null;
            text_status: components["schemas"]["TextStatus"];
            /**
             * Text Error
             * @description 提取失败时的原因说明
             */
            text_error?: string | null;
            /**
             * Task Count
             * @description 该文档下的抽取任务数，删除前提示用
             * @default 0
             */
            task_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Text Content
             * @description 提取出的完整纯文本
             */
            text_content?: string | null;
        };
        /**
         * DocumentOut
         * @description 文档摘要。不含正文——列表页拉 20 份文档的全文纯属浪费带宽。
         */
        DocumentOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Filename
             * @description 用户上传时的原始文件名，仅用于展示
             */
            filename: string;
            /** Mime Type */
            mime_type: string;
            /** Size Bytes */
            size_bytes: number;
            /**
             * Sha256
             * @description 内容指纹，可用于判断是否为同一份文件
             */
            sha256: string;
            /** Page Count */
            page_count: number | null;
            /**
             * Char Count
             * @description 提取到的文本字符数
             */
            char_count: number;
            /**
             * Text Preview
             * @description 正文前 500 字，供列表预览
             */
            text_preview: string | null;
            text_status: components["schemas"]["TextStatus"];
            /**
             * Text Error
             * @description 提取失败时的原因说明
             */
            text_error?: string | null;
            /**
             * Task Count
             * @description 该文档下的抽取任务数，删除前提示用
             * @default 0
             */
            task_count: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * ExtractionResultOut
         * @description 抽取结果。
         */
        ExtractionResultOut: {
            /**
             * Task Id
             * Format: uuid
             */
            task_id: string;
            /**
             * Data
             * @description 校验并规范化后的结构化数据
             */
            data: {
                [key: string]: unknown;
            };
            /**
             * Raw Output
             * @description 模型原始返回，用于排查结果可疑的情况
             */
            raw_output: string;
            /**
             * Warnings
             * @description 非致命问题清单
             */
            warnings?: components["schemas"]["TaskWarningOut"][];
            /**
             * Truncated
             * @description 输入文档是否因超长被截断
             */
            truncated: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LivenessOut */
        LivenessOut: {
            /** Status */
            status: string;
            /** App */
            app: string;
            /** Version */
            version: string;
            /** Environment */
            environment: string;
        };
        /** Page[DocumentOut] */
        Page_DocumentOut_: {
            /** Items */
            items: components["schemas"]["DocumentOut"][];
            /**
             * Total
             * @description 符合条件的总条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码，从 1 开始
             */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Pages
             * @description 总页数。空结果集返回 0 而不是 1，前端据此显示"暂无数据"。
             */
            readonly pages: number;
        };
        /** Page[TaskOut] */
        Page_TaskOut_: {
            /** Items */
            items: components["schemas"]["TaskOut"][];
            /**
             * Total
             * @description 符合条件的总条数
             */
            total: number;
            /**
             * Page
             * @description 当前页码，从 1 开始
             */
            page: number;
            /** Page Size */
            page_size: number;
            /**
             * Pages
             * @description 总页数。空结果集返回 0 而不是 1，前端据此显示"暂无数据"。
             */
            readonly pages: number;
        };
        /** ReadinessOut */
        ReadinessOut: {
            /** Status */
            status: string;
            /** Database */
            database: string;
        };
        /**
         * RejectedUpload
         * @description 批量上传中被拒绝的文件。
         */
        RejectedUpload: {
            /** Filename */
            filename: string;
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /**
         * StatsOut
         * @description 全局用量与成本统计。
         *
         *     "我知道每份文档花多少钱"是生产系统与 demo 的分水岭——
         *     这组数字直接回答"这个功能一个月要花多少钱"。
         */
        StatsOut: {
            /**
             * Total Documents
             * @description 已上传的文档总数
             */
            total_documents: number;
            /**
             * Total Tasks
             * @description 抽取任务总数
             */
            total_tasks: number;
            /** Completed Tasks */
            completed_tasks: number;
            /** Failed Tasks */
            failed_tasks: number;
            /**
             * Running Tasks
             * @description 尚未进入终态的任务数
             */
            running_tasks: number;
            /** Total Prompt Tokens */
            total_prompt_tokens: number;
            /** Total Completion Tokens */
            total_completion_tokens: number;
            /**
             * Total Reasoning Tokens
             * @description 其中思考 token（已含在 completion 内）
             */
            total_reasoning_tokens: number;
            /**
             * Total Cached Tokens
             * @description 命中前缀缓存的输入 token
             */
            total_cached_tokens: number;
            /** Total Cost Usd */
            total_cost_usd: number;
            /**
             * Avg Latency Ms
             * @description 已结束任务的平均耗时
             */
            avg_latency_ms?: number | null;
            /** Total Cost Cny */
            readonly total_cost_cny: number;
            /**
             * Success Rate
             * @description 成功率。
             *
             *     只统计**已结束**的任务——把还在排队的算进分母会让成功率虚低，
             *     用户看到"成功率 20%"会以为系统有问题，实际只是任务还没跑完。
             */
            readonly success_rate: number;
            /**
             * Avg Cost Per Task Usd
             * @description 单任务平均成本。用于回答"调大 max_tokens 值不值"。
             */
            readonly avg_cost_per_task_usd: number;
        };
        /** TaskCreateRequest */
        TaskCreateRequest: {
            /**
             * Document Ids
             * @description 要抽取的文档 ID 列表，1~50 个
             */
            document_ids: string[];
            /**
             * Template Key
             * @description 模板标识：内置模板用 contract / resume / invoice，自定义模板用 custom:<uuid>
             */
            template_key: string;
            /**
             * Batch Id
             * @description 批次 ID。不传则自动生成；同一批上传的文档传入相同值便于聚合展示
             */
            batch_id?: string | null;
        };
        /** TaskCreateResponse */
        TaskCreateResponse: {
            /**
             * Batch Id
             * Format: uuid
             */
            batch_id: string;
            /** Tasks */
            tasks: components["schemas"]["TaskOut"][];
        };
        /** TaskDeleteResponse */
        TaskDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * TaskOut
         * @description 任务摘要。用于列表与进度推送。
         */
        TaskOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Document Id
             * Format: uuid
             */
            document_id: string;
            /**
             * Document Filename
             * @description 来源文档的文件名，列表展示用
             */
            document_filename?: string | null;
            /** Template Key */
            template_key: string;
            /** Template Name */
            template_name: string;
            /** Batch Id */
            batch_id: string | null;
            status: components["schemas"]["TaskStatus"];
            /** Progress */
            progress: number;
            /**
             * Stage Message
             * @description 当前阶段的中文说明
             */
            stage_message?: string | null;
            /** Error Code */
            error_code?: string | null;
            /** Error Message */
            error_message?: string | null;
            /** Model */
            model?: string | null;
            /**
             * Prompt Tokens
             * @default 0
             */
            prompt_tokens: number;
            /**
             * Completion Tokens
             * @default 0
             */
            completion_tokens: number;
            /**
             * Reasoning Tokens
             * @description 思考 token，已包含在 completion_tokens 内
             * @default 0
             */
            reasoning_tokens: number;
            /**
             * Cached Tokens
             * @description 命中前缀缓存的输入 token
             * @default 0
             */
            cached_tokens: number;
            /**
             * Cost Usd
             * @default 0
             */
            cost_usd: number;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Attempts
             * @default 0
             */
            attempts: number;
            /** Started At */
            started_at?: string | null;
            /** Finished At */
            finished_at?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * TaskStatus
         * @description 抽取任务状态机。
         *
         *     .. code-block:: text
         *
         *         pending ──► parsing ──► extracting ──► validating ──► completed
         *            │           │            │             │
         *            └───────────┴────────────┴─────────────┴────────► failed
         *
         *     只有 completed / failed 是终态。
         * @enum {string}
         */
        TaskStatus: "pending" | "parsing" | "extracting" | "validating" | "completed" | "failed";
        /**
         * TaskWarningOut
         * @description 抽取过程中的一条非致命提示。
         */
        TaskWarningOut: {
            /**
             * Path
             * @description 出问题的字段路径，如 party_a 或 items[0].name
             */
            path: string;
            /**
             * Kind
             * @description 问题类型：missing_required / type_coerced / ...
             */
            kind: string;
            /** Message */
            message: string;
        };
        /** TemplateDeleteResponse */
        TemplateDeleteResponse: {
            /** Deleted */
            deleted: boolean;
        };
        /**
         * TemplateFieldOut
         * @description 模板中的一个字段。前端据此渲染结果卡片与表单标签。
         */
        TemplateFieldOut: {
            /** Name */
            name: string;
            /**
             * Label
             * @description 中文标签，前端用它替代字段名做展示
             */
            label: string;
            /** Type */
            type: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Required
             * @default false
             */
            required: boolean;
            /** Enum */
            enum?: string[];
            /** Item Type */
            item_type?: string | null;
            /** Item Fields */
            item_fields?: components["schemas"]["TemplateFieldOut"][];
        };
        /** TemplateOut */
        TemplateOut: {
            /** Key */
            key: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Doc Types
             * @description 适用的文档类型
             */
            doc_types?: string[];
            /**
             * Prompt Hint
             * @default
             */
            prompt_hint: string;
            /** Fields */
            fields?: components["schemas"]["TemplateFieldOut"][];
            /**
             * Builtin
             * @description 内置模板不可删除
             */
            builtin: boolean;
            /** Template Id */
            template_id?: string | null;
            /** Created At */
            created_at?: string | null;
        };
        /**
         * TextStatus
         * @description 文档文本提取结果。
         * @enum {string}
         */
        TextStatus: "extracted" | "no_text_layer" | "failed";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LivenessOut"];
                };
            };
        };
    };
    readiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessOut"];
                };
            };
        };
    };
    streamTasks: {
        parameters: {
            query?: {
                /** @description 逗号分隔的任务 ID，只看这些任务 */
                task_ids?: string | null;
                /** @description 只看某个批次 */
                batch_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTasks: {
        parameters: {
            query?: {
                /** @description 按状态过滤 */
                status?: components["schemas"]["TaskStatus"] | null;
                /** @description 按模板过滤 */
                template_key?: string | null;
                /** @description 按批次过滤 */
                batch_id?: string | null;
                /** @description 页码，从 1 开始 */
                page?: number;
                /** @description 每页条数，最大 100 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TaskOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    createTasks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TaskCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retryTask: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getResult: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                task_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExtractionResultOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listDocuments: {
        parameters: {
            query?: {
                /** @description 页码，从 1 开始 */
                page?: number;
                /** @description 每页条数，最大 100 */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_DocumentOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    uploadDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_uploadDocuments"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchUploadResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteDocument: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                document_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    listTemplates: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateOut"][];
                };
            };
        };
    };
    createCustomTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CustomTemplateOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deleteCustomTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TemplateDeleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOut"];
                };
            };
        };
    };
}
